# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_entries_password_info_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
