# Generated by Django 3.2.10 on 2022-02-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_encryptedpasswordprofiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesspassuser",
            name="key",
            field=models.TextField(blank=True, default=""),
        ),
    ]
