# Generated by Django 3.2.10 on 2022-02-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_lesspassuser_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="password",
            name="login",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="password",
            name="site",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
