# Generated by Django 3.2.10 on 2022-02-17 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_password_site_and_login"),
    ]

    operations = [
        migrations.RenameField(
            model_name="password",
            old_name="numbers",
            new_name="digits",
        ),
    ]
