#!/usr/bin/env bash
set -e

export COMPOSE_PROJECT_NAME=lesspass
docker-compose build
docker-compose down -v
docker-compose up -d
docker exec lesspass_backend_1 sh -c 'python wait_db.py'
docker exec lesspass_backend_1 sh -c 'python manage.py test'
docker-compose down -v
