# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site', models.CharField(max_length=255)),
                ('title', models.CharField(default=True, max_length=255, null=True)),
                ('username', models.CharField(default=True, max_length=255, null=True)),
                ('email', models.EmailField(default=True, max_length=254, null=True)),
                ('description', models.TextField(default=True, null=True)),
                ('url', models.URLField(default=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counter', models.IntegerField(default=1)),
                ('settings', models.TextField()),
                ('length', models.IntegerField(default=12)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PasswordInfo'),
        ),
    ]
