#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

python -m pip install --upgrade pip
python -m pip install -r requirements.txt
python -m pip install -r test-requirements.txt
export PYTHONPATH='.'
python -m unittest discover
