# Generated by Django 3.0.7 on 2020-07-25 23:26
import uuid
import binascii
import bcrypt
import hashlib
import json

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_change_default_password_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesspassuser',
            name='has_password_profile_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesspassuser',
            name='encryted_key',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='EncryptedPasswordProfiles',
            fields=[
                ('created', models.DateTimeField(
                    auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(
                    auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('password_profile', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='encrypted_password_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
