# Generated by Django 3.0.7 on 2020-12-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_change_default_password_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesspassuser",
            name="key",
            field=models.TextField(null=True),
        ),
    ]
