name: packages-test
on:
  push:
    branches:
      - main
    paths:
      - "packages/**"
  pull_request:
    paths:
      - "packages/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - run: yarn install
      - run: yarn build
      - run: yarn test
